fix: add missing esp_ieee802154.h include for set_txpower
esp_ieee802154_set_txpower() was called without the corresponding
header, causing an implicit-function-declaration error in GCC.

Resolves build failure:
  router.c:372: error: implicit declaration of function
  'esp_ieee802154_set_txpower' [-Wimplicit-function-declaration]